import cv2

IMAGE_RESIZE_INTERPOLATION = cv2.INTER_LINEAR
OUTLINE_RECTANGLE_THICKNESS = 5
OUTPUT_IMAGE_SIZE = (240, 240)
IMAGE_SIZE_DIVISOR = 14
SCALE_FACTOR = 1.2
MIN_NEIGHBORS = 3
CASCADE_CLASSIFIER_PATH = '../../resources/haarcascade_frontalface_alt.xml'
ORIGINAL_IMAGE_LABEL = 'original'
CROPPED_IMAGE_LABEL = 'cropped'
